### ISSUE TITLE
Is it possible to locate .dirsnap in the current folder?

### ISSUE THREAD

**Issue by UsulPro** [LanceTurri/dir-snap#3]
Hi! Thanks for creating this project! Looks like it exactly what I'm looking for!

In my case, I need to recreate the folder and check that the new one is the same as a previous. So I completely remove it and create from scratch each time. It would be great if I could keep `.dirsnap` not inside that but one level upper. What do you think?

And I'd like to install it not as a global dependency but as local devDependency of my project. I tried to do it with yarn workspaces but it fails after running `dirsnap reference` with error:

```console
$ node_modules/.bin/dirsnap -f test-gen/test-cdk-scripts/ -e js

  error: unknown option `-f'
```

Do you have any ideas why it goes wrong?

**Comment by LanceTurri** [comment]
Hey @UsulPro, I'm glad you like the module!

I think that's a great idea to be able to store the .dirsnap folder at an upper level, I'll get started on that this evening and will try to have a PR by Monday morning for this.

As to using it as a devDependency, I don't know why that would be failing, but I will try to reproduce it and get that fixed as well.

**Comment by LanceTurri** [comment]
@UsulPro I've added an option to the compare and reference commands to specify a custom reference folder storage location in version 0.3.0. That should allow you to run the snapshot, delete the folder, recreate it, and run the compare again using a folder outside of the child being examined.

In regards to using dir-snap as a devDependency, I'm having trouble recreating the issue. Instead of running the dirsnap file from the bin folder, try running dirsnap-reference and dirsnap-compare directly:

```sh
$ node_modules/bin/dirsnap-reference -f test-gen/test-cdk-scripts/ -e js
$ node_modules/bin/dirsnap-compare -f test-gen/test-cdk-scripts/ -e js
```

Let me know if you are still seeing the error.

**Comment by UsulPro** [comment]
Thanks @LanceTurri I'll try to test it

**Comment by LanceTurri** [comment]
@UsulPro Can I close this issue, or are you still testing?

**Comment by usulpro** [comment]
Thanks @LanceTurri I think it could be closed
